#!/bin/sh

xset -dpms
xset s off
xset s noblank

exec /usr/bin/chromium-browser http://0.0.0.0:8080/iqube/de/1 --window-size=480,320 --kiosk --incognito --noerrdialogs --fast --fast-start --disable-infobars --no-sandbox